services:
  - type: web
    name: hitster
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/app.db
      - key: YOUTUBE_API_KEY
        sync: false
